name: release-build
on: [push]
jobs:
  cargo-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rust MUSL Builder
        uses: NSCoder/rust-musl-action@v1.0.0
        env:
          BUILD_TARGET: x86_64-unknown-linux-musl
      - name: build
        run: cargo build --target $BUILD_TARGET --release
