name: push docker image

on:
  push:
    # # Enable when testing release infrastructure on a branch.
    # branches:
    #   - main
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  pick-version:
    name: pick-version
    runs-on: ubuntu-latest
    # env:
    #   # Set to force version number, e.g., when no tag exists.
    #   APP_VERSION: TEST-0.0.12
    outputs:
      app_version: ${{ env.APP_VERSION }}
      pj_name: ${{ env.PJ_NAME }}
    steps:
      - name: Get the release version from the tag
        shell: bash
        if: env.APP_VERSION == ''
        run: |
          # Apparently, this is the right way to get a tag name. Really?
          #
          # See: https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32167/highlight/true#M1027
          echo "APP_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "version is: ${{ env.APP_VERSION }}"
      - name: Get project name from github env
        shell: bash
        run: |
          echo "PJ_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV

  build-docker-image:
    name: build-docker-image
    needs: ['pick-version']
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USER: peccu
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./build
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USER }}/${{ needs.pick-version.outputs.pj_name }}:latest
            ${{ env.DOCKER_HUB_USER }}/${{ needs.pick-version.outputs.pj_name }}:${{ needs.pick-version.outputs.app_version }}
